# Generated by Django 5.0.4 on 2024-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Canceled', 'canceled')], max_length=50),
        ),
    ]
